service:
  name: graphql-baires-dev

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin  

custom:
  stageName: ${opt:s, 'staging'}
  dotenv:
      include:
      - PRUNE_BACKUP_NUMBER
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
      automatic: true
      includeLayers: true
      number: ${env:PRUNE_BACKUP_NUMBER}

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 30
  region: us-east-1
  deploymentBucket:
    name: deployment-bucket
  environment:
    NODE_ENV: ${self:custom.stageName}
    TZ: America/Sao_Paulo    

functions:
  graphql:
    handler: src/server.graphql
    events:
      - http:
          method: post
          path: graphql
          cors: true
      - http:
          method: get
          path: graphql  
          cors: true        